### ISSUE TITLE
[Bug]: No Lazy Load for the image_gen files

### ISSUE THREAD

**Issue by RafaelJohn9** [swarmauri/swarmauri-sdk#1051]
### Describe the Bug

```
 Exception ignored in: <function DeepInfraImgGenModel.__del__ at 0x7f82a3a01630>
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/swarmauri/llms/concrete/DeepInfraImgGenModel.py", line 192, in __del__
   self._client.close()
   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 871, in __getattr__
   return self.__pydantic_private__[item]  # type: ignore
   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 889, in __getattr__
    return super().__getattribute__(item)  # Raises AttributeError if appropriate
AttributeError: 'DeepInfraImgGenModel' object has no attribute '__pydantic_private__'
 INFO:gensim.utils:Doc2Vec lifecycle event {'params': 'Doc2Vec<dm/m,d3000,n5,w10,s0.001,t5>', 'datetime': '2024-12-23T22:15:46.991576', 'gensim': '4.3.3', 'python': '3.10.16 (main, Dec  4 2024, 20:37:01) [GCC 12.2.0]', 'platform': 'Linux-5.15.0-124-generic-x86_64-with-glibc2.36', 'event': 'created'}
```

This Error surfaces though there is no use of the ImgGenModel `DeepInfra`  

### Steps to Reproduce

When Trying to use `Doc2Vec` this error sprouts up.

### Software Version

Latest (Nightly Build)

### Python Version

Python 3.12

### Environment Details

Ubuntu 22.04 lts

### Relevant Logs or Error Output

```shell
edge_1               | Exception ignored in: <function DeepInfraImgGenModel.__del__ at 0x7f82a3a01630>
edge_1               | Traceback (most recent call last):
edge_1               |   File "/usr/local/lib/python3.10/site-packages/swarmauri/llms/concrete/DeepInfraImgGenModel.py", line 192, in __del__
edge_1               |     self._client.close()
edge_1               |   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 871, in __getattr__
edge_1               |     return self.__pydantic_private__[item]  # type: ignore
edge_1               |   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 889, in __getattr__
edge_1               |     return super().__getattribute__(item)  # Raises AttributeError if appropriate
edge_1               | AttributeError: 'DeepInfraImgGenModel' object has no attribute '__pydantic_private__'
edge_1               | INFO:gensim.utils:Doc2Vec lifecycle event {'params': 'Doc2Vec<dm/m,d3000,n5,w10,s0.001,t5>', 'datetime': '2024-12-23T22:15:46.991576', 'gensim': '4.3.3', 'python': '3.10.16 (main, Dec  4 2024, 20:37:01) [GCC 12.2.0]', 'platform': 'Linux-5.15.0-124-generic-x86_64-with-glibc2.36', 'event': 'created'}
```
```


### Additional Context (Optional)

_No response_

### Confirmation

- [X] I have searched the existing issues for this bug.
- [X] I have provided all necessary information to reproduce the bug.

**Comment by cobycloud** [comment]
resolved in 0.6.0 pre release
